### PR TITLE
added the syncing of redhat enabled repos

### PR DESCRIPTION
**Pull request by komidore64**
- added a `hammer_async` flag to run any capable tasks in async mode
- added a `bulldoze` flag which prevents the bash script from exiting
  if any command returns a nonzero exit status

### CODE REVIEW

**Comment by beav** [comment]
yay for bulldoze

**Comment by komidore64** [comment]
:+1:

**Comment by beav** [comment]
i didnt test the sync since it would take some time, but this looks good to me

ACK

**Comment by komidore64** [comment]
I tested out the sync yesterday

**Pull request merged**
